### ISSUE TITLE
Intellisense show 'rechdoc' comments when they cannot be used

### ISSUE THREAD

**Issue by spgennard** [RechInformatica/rech-editor-cobol#2]
To reproduce:

![image](https://user-images.githubusercontent.com/5991192/51142066-c3005d80-1842-11e9-8653-33071be725ec.png)

**Comment by GustavoASC** [comment]
This is a good suggestion. At this moment, RechDoc snippets are located in '.\snippets\cobol.json' which are always available in editor. 

We could programmatically add them in Language Server only and only if cursor is located on a RechDoc documentation.

**Comment by spgennard** [comment]
Closing, no action required
