### ISSUE TITLE
Turn Rech Editor Cobol extension Linux compatible 

### ISSUE THREAD

**Issue by gustavosimon** [RechInformatica/rech-editor-cobol#49]
This issue is to turn Rech Editor Cobol compatible with Linux OS.

The main problem is that some packages are declared with the incorrect case.

It makes that Language Server Provider crashes, and consequently the extension breaks together.

**Comment by GitMensch** [comment]
#50 was not directly linked to this issue, but was merged, so I _guess_ this should be closed.
